# Generated by Django 3.0.3 on 2020-02-28 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('std', models.IntegerField()),
                ('school', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Language1', models.IntegerField()),
                ('Language2', models.IntegerField()),
                ('Language3', models.IntegerField()),
                ('Maths', models.IntegerField()),
                ('Science', models.IntegerField()),
                ('Social', models.IntegerField()),
                ('Test_Date', models.DateField()),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simple_app.Child')),
            ],
        ),
        migrations.CreateModel(
            name='Sports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('running', models.IntegerField()),
                ('basketball', models.IntegerField()),
                ('cycling', models.IntegerField()),
                ('chess', models.IntegerField()),
                ('swimming', models.IntegerField()),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simple_app.Child')),
            ],
        ),
        migrations.CreateModel(
            name='English',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('communication', models.IntegerField()),
                ('Comprehensive', models.IntegerField()),
                ('Grammar', models.IntegerField()),
                ('Vocabulary', models.IntegerField()),
                ('Writing', models.IntegerField()),
                ('Aptitude', models.IntegerField()),
                ('LogicalReasoning', models.IntegerField()),
                ('GeneralMentalAbility', models.IntegerField()),
                ('MathSkills', models.IntegerField()),
                ('GeneralKnowledge', models.IntegerField()),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simple_app.Child')),
            ],
        ),
    ]
